### ISSUE TITLE
Improve debugging fail experience: deploying to incorrect board type

### ISSUE THREAD

**Issue by patridge** [WildernessLabs/VSCode_Meadow_Extension#15]
Just followed along with the [README](https://github.com/WildernessLabs/VSCode_Meadow_Extension#readme) and hit a few error messages that might be worth revising.

Since I did the `dotnet new` experience but deployed to a V1 Feather board, the resulting app refused to run (since it used `F7FeatherV2` instead of `F7FeatherV1`). When this happened, there was a logged debug message and a VS Code error pop-up. It sounds like this is intentional behavior when deploying to the wrong board now, so the error messages should probably be slightly more explicit about this being a blocker for users.

In the Debug Console tab, it logs this message. I didn't interpret this as a blocking issue for me, more as a warning (especially since I think this used to work, even if it wasn't a good thing).

> Meadow StdOut: Application is defined as F7FeatherV2, but running hardware is F7FeatherV1

And this is an error pop-up in VS Code when it gets to that point. (The lowercase "e" is from the actual error.) It's possible this error is a separate bug worth addressing: handling when the debugger doesn't attach successfully, maybe.

> error while processing request ‘stackTrace’ (exception: The vm is not suspended.)

**Comment by patridge** [comment]
If it helps debug anything, when I mistakenly hit F5 to start a new debug attempt, I was actually having it continue the current debugging session. So, maybe it was paused on a line somewhere.

When it did continue, it logged some Unhandled Exception output.

> Meadow StdErr: (System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
>   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in /root/myagent/_work/3/s/monobcl/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:936 
>    --- End of inner exception stack trace ---
>   at System.Re
> Meadow StdErr: lection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00015] in /root/myagent/_work/3/s/monobcl/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:944 
>   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00095] in /root/myagent/_work/3/s/monobcl/mcs/cl
> Meadow StdErr: ss/corlib/ReferenceSources/RuntimeType.cs:185 
>   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in /root/myagent/_work/3/s/monobcl/mcs/class/corlib/ReferenceSources/RuntimeType.cs:155 
>   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, S
> Meadow StdErr: stem.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in /root/myagent/_work/3/s/monobcl/mcs/class/referencesource/mscorlib/system/rttype.cs:5770 
>   at System.Activator.CreateInstance[T] () [0x00029] in /root/myagent/_work/3/s/monobcl/mcs/class/referencesource/mscorlib/system/activator.cs:236 
>   a
> Meadow StdErr:  Meadow.App`2[D,A]..ctor () <0xc0abc8b0 + 0x0000a> in <097253885cce43d68f3e9a9bd925a28e>:0 
>   at MeadowApp.MeadowApp..ctor () [0x00000] in /Users/patridge/Projects/WildernessLabs/_myprojects/MeadowNewVSCode20220706/MeadowApp.cs:15 
>   at MeadowApp.Program.Main (System.String[] args) [0x00001] in /Users/patridge/Projects/WildernessLabs/_myprojects/MeadowNewVSCode20220706/Program.cs:
> Meadow StdErr: 2
> Error receiving data from Visual Studio
> Meadow StdInfo: Mono is enabled
>

**Comment by CartBlanche** [comment]
@patridge, @nealef can I close this issue?

**Comment by patridge** [comment]
@CartBlanche I haven’t hit this issue recently. With all the recent changes, I’ll close it. If we see it again, we can revisit.
