### ISSUE TITLE
[Extension dev] Unable to build/debug extension locally

### ISSUE THREAD

**Issue by patridge** [WildernessLabs/VSCode_Meadow_Extension#21]
I initially tried started the extension in a local host instance with just <kbd>F5</kbd>. I loaded an existing Meadow project, but I never saw the status bar item show up for the Meadow device selection. I tried to align with the README steps, but so far the prerequisites and PowerShell build script haven't worked on my Intel macOS machine.

I have Mono installed, both via Visual Studio 2019/2022 and manually,, but it seems to be an issue here.

> % mono --version
> Mono JIT compiler version 6.12.0.182 (2020-02/6051b710727 Tue Jun 14 15:01:21 EDT 2022)

When I run the build script (`pwsh build.ps1`), I get these errors. So maybe I need to do something additional for Mono setup.

> /usr/local/share/dotnet/sdk/5.0.408/NuGet.targets(290,5): error MSB3202: The project file "/Users/patridge/Projects/WildernessLabs/VSCode_Meadow_Extension/externals/debugger-libs/Mono.Debugging/Mono.Debugging.csproj" was not found. [/Users/patridge/Projects/WildernessLabs/VSCode_Meadow_Extension/src/csharp/VSCodeMeadow.sln]
> /usr/local/share/dotnet/sdk/5.0.408/NuGet.targets(290,5): error MSB3202: The project file "/Users/patridge/Projects/WildernessLabs/VSCode_Meadow_Extension/externals/debugger-libs/Mono.Debugging.Soft/Mono.Debugging.Soft.csproj" was not found. [/Users/patridge/Projects/WildernessLabs/VSCode_Meadow_Extension/src/csharp/VSCodeMeadow.sln]
> /usr/local/share/dotnet/sdk/5.0.408/NuGet.targets(290,5): error MSB3202: The project file "/Users/patridge/Projects/WildernessLabs/VSCode_Meadow_Extension/externals/debugger-libs/Mono.Debugger.Soft/Mono.Debugger.Soft.csproj" was not found. [/Users/patridge/Projects/WildernessLabs/VSCode_Meadow_Extension/src/csharp/VSCodeMeadow.sln]
> /usr/local/share/dotnet/sdk/5.0.408/NuGet.targets(290,5): error MSB3202: The project file "/Users/patridge/Projects/WildernessLabs/VSCode_Meadow_Extension/externals/NRefactory/ICSharpCode.NRefactory/ICSharpCode.NRefactory.csproj" was not found. [/Users/patridge/Projects/WildernessLabs/VSCode_Meadow_Extension/src/csharp/VSCodeMeadow.sln]
> /usr/local/share/dotnet/sdk/5.0.408/NuGet.targets(290,5): error MSB3202: The project file "/Users/patridge/Projects/WildernessLabs/VSCode_Meadow_Extension/externals/NRefactory/ICSharpCode.NRefactory.CSharp/ICSharpCode.NRefactory.CSharp.csproj" was not found. [/Users/patridge/Projects/WildernessLabs/VSCode_Meadow_Extension/src/csharp/VSCodeMeadow.sln]

If I just hit F5 instead, I get other errors, but they could be a result of the build script not working.

While working from the code in #18, triggering the device picker command would cause a "Command failed" error.

> Command 'Meadow: Select device' resulted in an error (Command failed with exit code 1: dotnet /Users/patridge/Projects/WildernessLabs/VSCode_Meadow_Extension/src/csharp/bin/Debug/net5.0/vscode-meadow.dll util -c=devices
> Could not execute because the specified command or file was not found.
> Possible reasons for this include:
> * You misspelled a built-in dotnet command.
> * You intended to execute a .NET program, but dotnet-/Users/patridge/Projects/WildernessLabs/VSCode_Meadow_Extension/src/csharp/bin/Debug/net5.0/vscode-meadow.dll does not exist.
> * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.)

**Comment by CartBlanche** [comment]
@patridge Sorry about the very late reply. I can sync with your this week, if you are still unable to build any extensions.
