### ISSUE TITLE
Error "Cannot read property 'extensionPath' of undefined" when trying to debug

### ISSUE THREAD

**Issue by cutty225** [WildernessLabs/VSCode_Meadow_Extension#5]
I have installed the latest version of the VSIX (0.18.7)

I have the latest version of Meadow CLI installed (v0.15.1) and Meadow device is flashed to 0.6.0.0

I have created the sample app using the template which I can manually deploy to the meadow using meadow app deploy -f App.exe and it runs fine.

If I try to debug inside VS code, using Run -> Start Debugging I see a popup message "Cannot read property 'extensionPath' of undefined".

**Comment by cutty225** [comment]
On investigating using the debug console in VS Code it would appear that the issue is due to the extension being installed in a folder 'wilderness labs.meadow-0.18.7' (note the space) but when calling getExtension it is using wildernesslabs.meadow (no space).

**Comment by cutty225** [comment]
Update - have tried downloading and installing the latest VSIX 0.19.0 and getting the same issue, though a slightly different error message:  "Cannot read properties of undefined (reading 'extensionPath')"

**Comment by CartBlanche** [comment]
@cutty225 I have a new VSIX. Let me know how I can send it to you. Once you confirm it works for you (and not just on my machine :) ) I'll upload the Release on this repo with the new VSIX.

**Comment by cutty225** [comment]
Hi Dominique,

 

I have created a public folder at https://drive.google.com/drive/folders/1YcZqz3GiCPIRwpuPwK7ReTRDVwf26pMk?usp=sharing . You should be able to upload it there. Let me know when it’s there and I’ll give it a try.

 

Cheers,

 

Iain

**Comment by cutty225** [comment]
@CartBlanche That version is working perfectly! Deploy and debug are now working from VSCode. Thank you so much for investigating and fixing. I can finally, start playing with my Meadow. Ripper!
