### ISSUE TITLE
Bump to .NET 8 to reduce SDK install requirements?

### ISSUE THREAD

**Issue by patridge** [WildernessLabs/VSCode_Meadow_Extension#95]
Request: 
Update VS Code Extension to use .NET 8 instead of .NET 7 to match CLIv2

Context:

With the CLIv2 moving to .NET 8, there is a slight disconnect. If you _only_ install .NET 8, you will hit an error in VS Code when you try to run the Meadow command saying you need .NET 7 installed. Once you install both, you should be fine in both CLIv2 and VS Code.

![VS Code error saying 'Meadow: Select device' resulted in an error saying you need to install .NET 7.0.0 (arm64).](https://github.com/WildernessLabs/VSCode_Meadow_Extension/assets/713665/c2e2ed47-00c7-4c3e-a19f-2821830a0976)

**Comment by shawnshekari** [comment]
![image](https://github.com/WildernessLabs/VSCode_Meadow_Extension/assets/602278/fa8516ad-b3de-4cc2-a791-63111f590be6)

Same issue here, I guess I will force install 7 to resolve for now.

**Comment by CartBlanche** [comment]
@patridge, @shawnshekari could you please grab the artefact from this CI build, `v1.9.2`, and let me know if this works for you - https://github.com/WildernessLabs/VSCode_Meadow_Extension/actions/runs/8121636404

**Comment by shawnshekari** [comment]
I grabbed it and installed it, but I am still seeing a reference to .net 7.
![image](https://github.com/WildernessLabs/VSCode_Meadow_Extension/assets/602278/8da3e63c-45ae-4a14-8a61-e801ba4d2b4e)

I get that using the when using the key binding for Meadow: Select Device

Confirming the version installed.
![image](https://github.com/WildernessLabs/VSCode_Meadow_Extension/assets/602278/e93db90c-45f0-4f1c-a7f4-8542be464609)

**Comment by CartBlanche** [comment]
@shawnshekari Seems I missed some net7.0 references. Could try this build when it's finished - https://github.com/WildernessLabs/VSCode_Meadow_Extension/actions/runs/8131353380

**Comment by shawnshekari** [comment]
Works great now, thank you!
